import type { ServerBuild } from '@vercel/remix';
import { createRequestHandler } from '@vercel/remix';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

export default createRequestHandler({
  build: serverBuild as unknown as ServerBuild,
});
